title: 'Bitdevs Interior'
tagline: 'Bitdevs Ã© uma comunidade para aqueles interessados em discutir e participar na pesquisa e desenvolvimento do Bitcoin e protocolos relacionados.'

menu:

  - {name: 'Eventos', url: '/events'}
  - {name: 'Meetup', url: 'https://lu.ma/5i2q0di6', external: true}
